### ISSUE TITLE
Rcon returning not enabled with testannounce

### ISSUE THREAD

**Issue by njhughes-01** [Diyagi/vrising-server-docker#11]
I am getting an rcon not enable msg when I attempt to use the testannounce feature that was added

![image](https://github.com/Diyagi/vrising-server-docker/assets/20962973/e766e4bd-13a7-4968-ab2e-6c4483a8cf1f)

```
services:
  vrising:
    image: diyagi/vrising-server-docker:latest
    restart: unless-stopped
    stop_grace_period: 15s
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
      - 25575:25575
    environment:
      TZ: "America/Chicago"
      PUID: 1001
      PGID: 1001
      VR_NAME: "[NA][CST] Bloodspace PVP No Wipe 2x Harvest No Raids"
      VR_DESCRIPTION: "Reduced durability loss no corpse loot no raid A Blood META Project"
      VR_GAME_PORT: 27015
      VR_QUERY_PORT: 27016
      VR_RCON_PORT: 25575
      VR_LIST_ON_EOS: "true"
      VR_LIST_ON_STEAM: "true"
      VR_SAVE_NAME: "world1"
      VR_RCON_ENABLED: "true"
      VR_RCON_PASSWORD: "G*"
      COMPILE_GAME_SETTINGS: "false"
      COMPILE_HOST_SETTINGS: "false"
      AUTO_UPDATE_CRON_EXPRESSION: "0 6 * * *"
      AUTO_UPDATE_ENABLED: "true"
      AUTO_ANNOUNCE_ENABLED: "true"
      AUTO_ANNOUNCE_CRON_EXPRESSION: "*/20 * * * *"
    volumes:
    - /mnt/toth/Backup/steamHosting/vRising1/server:/vrising/server
    - /mnt/toth/Backup/steamHosting/vRising1/data:/vrising/data
    - /mnt/toth/Backup/steamHosting/vRising1/announce:/vrising/announce

```

Am I missing something obvious as when I attempt to connect to rcon with the host system everything is fine. 

I also tried to compile_host_setting enabled
